import { cancerLabels, researchNotice } from "./types";
import type { Analysis, Message } from "./types";
const escape = (text: string) =>
  text.replace(
    /[&<>"']/g,
    (char) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        char
      ]!,
  );
export async function downloadReport(
  analysis: Analysis,
  file: File,
  messages: Message[],
) {
  const image = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () =>
      reject(new Error("Could not read your image. Please try again."));
    reader.readAsDataURL(file);
  });
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>LifeLens research report</title><style>body{font:16px/1.6 system-ui,sans-serif;color:#203c36;max-width:850px;margin:48px auto;padding:24px}h1{font-size:36px;letter-spacing:-1px}h2{margin-top:32px}dl{display:grid;grid-template-columns:1fr 1fr;gap:12px}dt{color:#60736d}dd{margin:0;font-weight:600}img{width:100%;max-height:360px;object-fit:contain;border-radius:12px}.images{display:grid;grid-template-columns:1fr 1fr;gap:24px}.notice{padding:20px;background:#edf5f1;border-radius:12px}p{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:600px){.images{grid-template-columns:1fr}}@media print{body{margin:0}img{max-height:240px}}</style></head><body><p>LifeLens · Research workspace</p><h1>Image analysis report</h1><p>${escape(new Date(analysis.completedAt).toLocaleString())}</p><div class="notice">${escape(researchNotice)}</div><h2>Analysis overview</h2><dl><dt>Model</dt><dd>${cancerLabels[analysis.cancerType]}</dd><dt>File</dt><dd>${escape(file.name)}</dd><dt>Model prediction</dt><dd>${analysis.diagnosis}</dd><dt>Model confidence</dt><dd>${analysis.certainty_percent.toFixed(2)}%</dd><dt>Model risk indicator</dt><dd>${analysis.riskLevel}</dd></dl><p>Model confidence is not the probability of having cancer. The risk indicator is a heuristic derived from the model output, not a clinical assessment.</p><div class="images"><div><h2>Original image</h2><img src="${escape(image)}" alt="Original uploaded image"></div><div><h2>Model attention</h2>${analysis.gradcam_overlay ? `<img src="${escape(analysis.gradcam_overlay)}" alt="Grad-CAM model attention">` : "<p>No attention map available.</p>"}</div></div><p>Grad-CAM visualizes regions influencing the model prediction. It does not identify or localize cancer.</p>${messages.length ? `<h2>Conversation</h2>${messages.map((m) => `<p><strong>${m.role === "user" ? "You" : "LifeLens"}</strong><br>${escape(m.content)}</p>`).join("")}` : ""}<hr><p>Generated by LifeLens. Open this file in a browser and use Print to save a PDF.</p></body></html>`;
  const url = URL.createObjectURL(
    new Blob([html], { type: "text/html;charset=utf-8" }),
  );
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `lifelens-${analysis.cancerType}-${analysis.completedAt.slice(0, 10)}.html`;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
